spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dental_system
    username: "db username"
    password: "db password"


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
      check_nullability: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect








